"""Add img field for cards

Revision ID: 959188031450
Revises: 
Create Date: 2021-06-02 21:54:35.098829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '959188031450'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('img', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'img')
    # ### end Alembic commands ###
